### ISSUE TITLE
Android error

### ISSUE THREAD

**Issue by NirMiron** [TheOriginalJosh/nativescript-weather#21]
Hi,
When running on android i get the following error:  " Cannot read property 'unit' of undefined"

here is the full log
JS: Angular is running in the development mode. Call enableProdMode() to enable the production mode.
JS: select card 
JS: DPI - 548.5714285714286
JS: DPI - 548.5714285714286
JS: DPI - 548.5714285714286
JS: DPI - 548.5714285714286
JS: ERROR TypeError: Cannot read property 'unit' of undefined
JS: ERROR CONTEXT [object Object]
JS: ERROR TypeError: Cannot read property 'unit' of undefined
JS: ERROR CONTEXT [object Object]
JS: ERROR Error: Uncaught (in promise): TypeError: Cannot read property 'unit' of undefined
JS: TypeError: Cannot read property 'unit' of undefined
JS:     at Object.toDevicePixelsCommon [as toDevicePixels] (file:///data/data/org.joshdsommer.weathercards/files/app/tns_modules/tns-core-modules/ui/styling/style-properties.js:55:19)
JS:     at valueChanged (file:///data/data/org.joshdsommer.weathercards/files/app/tns_modules/tns-core-modules/ui/layouts/absolute-layout/absolute-layout-common.js:42:53)
JS:     at AbsoluteLayout.Property.Property.options.set [as left] (file:///data/data/org.joshdsommer.weathercards/files/app/tns_modules/tns-core-modules/ui/core/properties/properties.js:91:25)
JS:     at ViewUtil.setPropertyInternal (file:///data/data/org.joshdsommer.weathercards/files/app/tns_modules/nativescript-angular/view-util.js:172:32)
JS:     at ViewUtil.setProperty (file:///data/data/org.joshdsommer.weathercards/files/app/tns_modules/nativescript-angular/view-util.js:133:18)
JS:     at NativeScriptRenderer.setProperty (file:///data/data/org.joshdsommer.weathercards/files/app/tns_modules/nativescript-angular/renderer.js:130:30)
JS:     at DebugRenderer2.setProperty (file:///data/data/org.joshdsommer.weathercards/files/app/tns_modules/@angular/core/bundles/core.umd.js:13461:23)
JS:     at setElementProperty (file:///data/data/org.joshdsommer.weathercards/files/app/tns_modules/@angular/core/bundles/core.umd.js:9586:19)
JS:     at checkAndUpdateElementValue (file:///data/data/org.joshdsommer.weathercards/files/app/tns_modules/@angular/core/bundles/core.umd.js:9505:13)
JS:     at checkAndUpdateElementInline (file:///data/data/org.joshdsommer.weathercards/files/app/tns_modules/@angular/core/bundles/core.umd.js:9445:24)
JS:     at checkAndUpdateNodeInline (file:///data/data/org.joshdsommer.weathercards/files/app/tns_modules/@angular/core/bundles/core.umd.js:12238:23)
JS:     at checkAndUpdateNode (file:///data/data/org.joshdsommer.weathercards/files/app/tns_modules/@angular/core/bundles/core.umd.js:12184:16)
JS:     at debugCheckAndUpdateNode (file:///data/data/org.joshdsommer.weathercards/files/app/tns_modules/@angular/core/bundles/core.umd.js:12887:59)
JS:     at debugCheckRenderNodeFn (file:///data/data/org.joshdsommer.weathercards/files/app/tns_modules/@angular/core/bundles/core.umd.js:12866:13)
JS:     at Object.eval [as updateRenderer] (ng:///AppModule/ForecastCardComponent.ngfactory.js:257:5)

Thanks
Nir

**Comment by karanianandkumar** [comment]
I am also facing the same problem. Any suggestions?
